### ISSUE TITLE
Mon contenu a disparu et ne s'enregistre plus

### ISSUE THREAD

**Issue by bplume** [simonvdfr/Translucide#16]
J'ai trouvé l'erreur. C'était un div en trop qui trainait. Ce qui a provoqué l'effacement de tout ce qu'il y avait en dessous en ce qui concerne les textes. J'aimerais tout de même savoir s'il y a moyen de faire une sauvegarde du contenu. Merci.
Sujet clos, sinon. 

Bonjour,
Alors que j'avais intégré tous mes textes il y a quelques jours sans problème. Aujourd'hui, en travaillant sur mon site, tout d'un coup, tout mon contenu a disparu de la page à part 3 pavés, ainsi que toutes les illustrations. Alors que j'étais juste en train, de finir de travailler sur un texte. J'ai beau essayer de le retaper, il ne s'enregistre pas dès que j'actualise.
Merci de me dire comment cela a pu se produire et s'il y a moyen de faire une sauvegarde une fois que tout est intégré pour éviter ce genre de problème.
Bien cordialement,
Béatrice.

**Comment by simonvdfr** [comment]
Bonjour,
Dans une logique de sobriété nous n'avons pas implémenté un système de backup, surtout que souvent il y a en a un sur les hébergements.
