### ISSUE TITLE
Class et Alt pour les images

### ISSUE THREAD

**Issue by boudermarion** [simonvdfr/Translucide#17]
Bonjour,

Je viens de découvrir votre CMS et après quelques tests je m'interroge sur la manière dont on peut insérer des class pour les images `<?php media('media-2', '650')?>` et comment renseigner les balises alt. 

Je n'ai probablement pas suffisamment cherché donc je vais continuer ;)

Merci

**Comment by simonvdfr** [comment]
Bonjour,

Pour les alt ils sont éditables une fois dans le mode édition du CMS. Au passage au dessus de la zone média, quand il y a une image, il y a un champ pour rentrer le texte alternatif.

pour spécifier une class :
`media('media-2', array('class'=>'nomdemaclass', 'size'=>'650'))`

Simon

**Comment by boudermarion** [comment]
C'est parfait, mes tests sont vraiment concluants. Merci 🙂
