### ISSUE TITLE
Ajouter des icones aux items du menu

### ISSUE THREAD

**Issue by marionbouder** [simonvdfr/Translucide#18]
Bonjour,

Je souhaiterais ajouter des icones différents à chaque item de mon menu. Est-ce possible d'en ajouter (type fontawesome) ou à défaut des images spécifiques.

Peut-on spécifier quelque chose au niveau de `.$val['text'].` dans le fichier header.php ?

Merci :)

**Comment by marionbouder** [comment]
Bonsoir,

Alors j'ai trouvé une solution, le rendu me convient très bien !
![image](https://user-images.githubusercontent.com/52031508/115970562-6e7cda00-a543-11eb-9dbe-07362871ed8b.png)

Voilà ce que j'ai fait pour ceux qui seraient intéressés : 
- dans le header déclarer une class à nav 
  -> dans mon exemple : `<nav class="menu-icon">`
- dans le css de mon thème -> ajouter les paramètres qui permettent de choisir les bons icones 
  -> dans mon exemple : `.menu-icon ul li::before{	font-family: 'simple-line-icons'; line-height: 1; margin-right: 2rem; color: #ff4c60!important;} et .menu-icon ul li:nth-of-type(1)::before  {content: '\e069';} /*affiche l'icone home devant le premier item du menu*/`

**Comment by simonvdfr** [comment]
Vous pouvez aussi activer l'accès aux icônes dans la barre d'outil d'édition de texte 
`$GLOBALS['toolbox']` enlever le commentaire devant la ligne `icon`

et vous pouvez également charger votre propre librairie d'icones dans config : `$GLOBALS['icons'] = "https://urldevotrelibrairie";`
