### ISSUE TITLE
Paramètres config.php

### ISSUE THREAD

**Issue by marionbouder** [simonvdfr/Translucide#19]
Bonjour,

Je viens de terminer ma migration vers translucide et suis vraiment très satisfaite, vous pouvez aller jeter un œil [ici](https://marion.bouder.me).
Quelques interrogations quant aux paramétrages de `config.php`.

J'ai bien modifié les informations présentent dans "[A faire à la mise en ligne](https://github.com/simonvdfr/Translucide#a-faire-%C3%A0-la-mise-en-ligne)" mais aucun changement de paramètres ne semble être pris en compte. Je m'explique :
- `$GLOBALS['scheme']` en `https` > pages inaccessibles (sauf accueil). J'ai donc modifié mon htaccess et repassé en http dans `config.php`
- `$GLOBALS['online']` en `true` > pas de différence
- `$GLOBALS['min']` en `.min` > toujours `style.css` de chargé

Une idée, quelque chose que j'aurais loupé ?

Merci et bonne journée.

**Comment by simonvdfr** [comment]
vous modifiez bien les paramètres dans la 2ème condition (pas pour l’environnement de dev :  $dev) ?
`if($dev)
$GLOBALS['scheme'] = "http://";
else 
$GLOBALS['scheme'] = "https://";`

`$GLOBALS['online']` semble est bon car le site est bien en index+follow `<meta name="robots" content="index, follow" data="">`

**Comment by marionbouder** [comment]
Pour le `$GLOBALS['scheme']` Oui, la 2ème condition, et il me redirige constamment vers ce message (même sur nouveau navigateur, sans historique, sans cookies et cache vidé)
![image](https://user-images.githubusercontent.com/52031508/116415661-eac03780-a839-11eb-9501-b11ca478f7a5.png)

Bon avec la solution via `.htaccess` pas de problème donc tout va bien mais je trouve ça assez étrange

Pour le `$GLOBALS['online']` -> ok

**Comment by JokerMedical** [comment]
Bonjour @simonvdfr et @marionbouder,
J'ai exactement le même problème, avec les trop nombreuses redirections...
@marionbouder vous parlez d'une solution avec le .htaccess, j'en ai essayé plusieurs, mais toujours le même résultat. Puis-je vous demandez ce que vous avez fait pour que cela marche ?
Merci de votre retour.
Une agréable journée.

**Comment by simonvdfr** [comment]
@JokerMedical il n'est probable que vous ayez le même problème que @marionbouder avec votre configuration en local qui ne renvoi par la variable `$dev` à  `true`.
c'est peut-être due à votre config apache qui ne renvoi pas l'ip 127.0.0.1 pour votre adresse de serveur.
essayer de mettre tous les  `$GLOBALS['scheme'] = "http://";` ou forcer la variable `$dev` sur `true`

vous avez quoi dans votre variable `$_SERVER['SERVER_ADDR']` ?
