### ISSUE TITLE
Nginx

### ISSUE THREAD

**Issue by Thatoo** [simonvdfr/Translucide#22]
Is it possible to install Translucide with Nginx instead of Apache2?

I have tried with a very stadard nginx conf file but it doesn't work : 
```
server {
        root /var/www/html/translucide;
        index index.php;
        server_name mywebsite.fr;

        location / {
                try_files $uri $uri/ =404;
        }
        location ~ \.php$ {
               include snippets/fastcgi-php.conf;
               fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        }
}
```
I mean, the first page display but as soon as I click on a link, I get a 404 page.

**Comment by Thatoo** [comment]
Est-il possible d'installer Translucide avec Nginx au lieu d'Apache2 ?

J'ai essayé avec un fichier de conf très standard de Nginx mais cela ne fonctionne pas :

```
server {
        root /var/www/html/translucide;
        index index.php;
        server_name mywebsite.fr;

        location / {
                try_files $uri $uri/ =404;
        }
        location ~ \.php$ {
               include snippets/fastcgi-php.conf;
               fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        }
}
```
Je veux dire, la première page s'affiche mais dès que je clique sur un lien, j'obtiens une page 404.

**Comment by Thatoo** [comment]
Je crois que j'ai trouvé mais je suis preneur de tous commentaires et d'amélioration

```
server {
        root /var/www/html/translucide;
        index index.php;
        server_name mywebsite.fr;

#        location = /robots.txt {
#                allow all;
#                log_not_found off;
#                access_log off;
#        }

        location / {
                try_files $uri $uri/ /index.php?$args =404;
        }
        location ~ \.php$ {
               include snippets/fastcgi-php.conf;
               fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        }
}
```

Pour l'instant je laisse commenter la partie sur le fichier robots.txt mais je décommenterai quand mon site sera live.
J'ai d'ailleurs ouvert une question au sujet des robots et de la sitemap : https://github.com/simonvdfr/Translucide/issues/23

**Comment by Thatoo** [comment]
So yes, it is possible to use Translucide with nginx and even behind a revers proxy nginx.

**Comment by simonvdfr** [comment]
Bonjour,

Le CMS est fait pour s'installer sur la plupart des hébergements mutualisés, qui sont majoritairement sous Apache.
Nous n'avons jamais fait d'installation sous Nginx. Ce qui est important c'est de rediriger toutes les URL vers index.php qui lui se charge de récupérer le contenu en fonction de l'URL.

Simon
