### ISSUE TITLE
Sitemap et SEO

### ISSUE THREAD

**Issue by Thatoo** [simonvdfr/Translucide#23]
Est-ce qu'il y a une sitemap qui se tient à jour?
Comment bien renseigner les robots de google et autres moteurs de recherche pour faire de l'optimisation pour les moteurs de recherche (SEO)?

**Comment by Thatoo** [comment]
Je viens de découvrir qu'il existe un plugin, https://github.com/simonvdfr/Translucide-Plugin/blob/master/sitemap.php.
Si je comprends bine, il faut que je crée un dossier "PLugin" à la racine du serveur, à côté de "api" et que j'ajoute ce fichier dedans.
Et ensuite, comment l'active t-on?
On rajoute une ligne dans index.php " include_once("pugin/sitemap.php");// Plugin de Sitemap " ?

```
<?php
// Vérifie la configuration de short open tag // Supp 6 mois après le 22/10/2020
//if(!ini_get('short_open_tag')) exit('Please put "short_open_tag = On" in php.ini');

@include_once("config.php");// Variables
include_once("api/function.php");// Fonctions
include_once("api/db.php");// Connexion à la db
include_once("pugin/sitemap.php");// Plugin de Sitemap
```

**Comment by Thatoo** [comment]
Ne pourrait-on pas ajouter cette fonction plutôt?

```
foreach (glob("plugin/*.php") as $filename)
{
    include_once $filename;
}
```

Soit

<?php
// Vérifie la configuration de short open tag // Supp 6 mois après le 22/10/2020
//if(!ini_get('short_open_tag')) exit('Please put "short_open_tag = On" in php.ini');

@include_once("config.php");// Variables
include_once("api/function.php");// Fonctions
include_once("api/db.php");// Connexion à la db
include_once("pugin/sitemap.php");// Plugin de Sitemap
foreach (glob("plugin/*.php") as $filename)
{
    include_once $filename;
}

**Comment by Thatoo** [comment]
@simonvdfr si tu valides avec un pouce en l'air mes commentaires, je fais des PR pour
- Nginx (je propose un modèle de fichier et j'explique dans le Readme : pouce en l'air https://github.com/simonvdfr/Translucide/issues/22#issuecomment-917093412
- Cette proposition de fonction pour activer automatiquement les plugins : pouce en l'air juste au dessus
- Mettre à jour le Readme : la mention des extensions PHP nécessaires et la suppression de la mention short_open_tag = On dans Readme et dans index.html : pouce en l'air https://github.com/simonvdfr/Translucide/pull/21

**Comment by Thatoo** [comment]
Ah ben non, ma proposition de fonction n'est valable que pour les plugins en PHP or il y en a avec un ficher .js aussi.
Je n'ai pas dû bien comprendre comment les plugins étaient implémenté et appelé dans index.html.
Merci par avance de bien vouloir m'éclairer pour que je puisse faire un PR utile.

**Comment by simonvdfr** [comment]
- pour le sitemap pas besoin de l'intégrer dans le code. il faut le soumettre à la Search Console de google ou/et l'ajouter dans les robots.txt
c'est une option à implémenter en fonction de chaque client. pour éviter de rajouter du code dans le cms nous préférons ajouter au cas par client.

- pour nginx ne connaissant pas bien ce système nous préférerions avoir d'autre retour avant d'ajouter dans la documentation des informations à ce sujet.

- pour le readme.md j'ai fait quelques modifications et ajouter vos recommandations sur les extensions (qui sont déjà sur tous les hébergements mutualisés)

**Comment by Thatoo** [comment]
@simonvdfr Merci pour vos réponses. OK pour robots.txt, OK pour Nginx, OK pour Reradme.

> pour éviter de rajouter du code dans le cms nous préférons ajouter au cas par client.

Je ne vais parler ici que des plugins en php qui s'ajoute avec un simple include. Pour ceux qui ont du js, je n'ai pas compris comment c'était géré.
Si on ajoute ce code
foreach (glob("plugin/*.php") as $filename)
{
    include_once $filename;
}
dans index.php, ça n'ajoute aucun plugin tant que le dossier plugin est vide.
Ca n'alourdit que de très peu le code mais ça facilite l'ajout/suppression de plugin puisqu'il suffit d'ajouter ou de supprimer le fichier .php du dossier et c'est tout. Il ne faut pas en plus ajouter ou supprimer une ligne include. Qu'en pensez-vous?
