### ISSUE TITLE
Video (mp4/ogg/webm)?

### ISSUE THREAD

**Issue by Thatoo** [simonvdfr/Translucide#32]
Est-ce possible d'afficher une video (mp4/ogg/webm), même dans un lecteur html5 tout simple?
Pour l'instant je n'ai trouvé qu'à afficher du gif mais bon une toute petite video de 20 seconde en mp4 de 12 Mo, pèse 280 Mo une fois en gif...
L'autoplay et le préchargement iraient contre l’écoconception donc uniquement les boutons play/pause et plein écran.

**Comment by simonvdfr** [comment]
Je pense que oui, après effectivement il faut faire très attention, car une vidéo va gréver ton budget écoconception très très fortement. il faut reculer son utilisation au maximum.
tu peux dans le fichier config autorisé l'upload de ce type de fichier dans la variable `mime_supported`.
ensuite il faut trouver comment l'afficher, avec un lecteur HTML5.
on ne gère pas nativement ce genre de chose car on va éviter le plus possible de mettre des vidéos dans les sites.
La seule fonction en lien avec les vidéos c'est l'option dans la `toolbox` qu'il faut activé dans la config `vidéo`. ça te permet de mettre une URL Youtube facilement, et ça intègre dans le contenu une image qui aux clique injectera le lecteur Youtube. ça permet de ne pas charger la vidéo et le player si l'utilisateur ne veut pas regarder la vidéo...

**Comment by Thatoo** [comment]
L'option dans la toolbox n'existe pas dans cette version on dirait : https://github.com/simonvdfr/Translucide/releases/tag/v1.0

A mon avis, un lecteur HTML5 intégré ne pèsera pas bien lourd dans le budget écoconception si par défaut il ne précharge pas les vidéos.

D'un point de vue respect de la vie privée, il vaut mieux qu'une vidéo soit lue depuis le site plutôt que depuis Youtube. Et si on fait un effort pour ne mettre que le strict minimum de vidéo et avec une basse résolution, ça pourrait même être mieux que de faire appel à Youtube, non?

**Comment by simonvdfr** [comment]
Bonjour,

Le v1.0 est bien ancienne maintenant. je vous recommande de télécharger la dernière en cours qui inclut cette fonction pour Youtube : https://github.com/simonvdfr/Translucide/archive/refs/heads/master.zip
À la fin du projet en cours (d'ici quelques mois) je pense que je créerais une version 1.5 stables qui de plus aura un thème plus accessible que l'actuel.

Effectivement ça peut être intéressant d'utiliser le player HTML 5 niveau éthique. ne pas précharger la vidéo. la lancer uniquement à la demande et dans une résolution minime. le seul avantage qui resterait à YouTube c'est qu'il adapte le flux à la connexion, propose une version compatible avec les anciens navigateurs, propose une expérience plus accessible par défaut, et potentiellement une transcription pour les personnes qui ont un handicap.

Un player HTML 5 plus des transcriptions textuelles (dans votre HTML, ou un fichier à télécharger) serrai une bonne alternative.

Vous pouvez très bien créer un input qui apparaît qu'en mode admin, ou vous coller l'URL de votre fichier mp4, et après vous pouvez récupérer la variable pour l'injecter dans le player HTML 5 : `input('mp4', array("type" => "hidden"));`

**Comment by simonvdfr** [comment]
j'ai approuvé votre suggestion de code pour l'ajout de vidéo pour la fonction `media()`

**Comment by Thatoo** [comment]
C'est une super nouvelle cette v1.5 à venir!

Pour toutes les raisons que vous évoquez concernant Youtube, mieux encore ce serait de pouvoir intégrer une video peertube.

Dans ma proposition de code, je n'avais mis que mp4. Voulez-vous que je fasse une PR pour webm aussi?

**Comment by Thatoo** [comment]
C'est super!
Je me suis permis de faire un autre PR pour simplement pouvoir choisir la largeur qu'on souhaite afficher pour la video au sein de la page.

Par ailleurs, je n'arrive pas très bien à coder ça dans mon thème.
Comme on ne peut pas encore ajouter une vidéo dans un bloc article comme c'est le cas pour une image, je suis aussi obligé de découper page_video.php en trois, un bloc article, un bloc media et encore un bloc article ce qui done:

```
<section class="mw1140p mod center">
	<article class="tj pll prl ptm">
		<?php txt('texte1')?>
	</article>
	<div class="tc pll prl">
			<?php media("item-video-1", '480');?>
	</div>
	<article class="tj pll prl pbl">
			<?php txt('texte2')?>
	</article>
</section>
```
Ça fonctionne mais seulement si j'ajoute la video en tout dernier, juste avant d'appuyer sur le bouton enregistrer.
Si jamais je ré-édite la page et que j'appuie sur enregistrer, alors la video ne s'affiche plus. Je dois ré-éditer pour rajouter la video uniquement et alors ça refonctionne.

**Comment by Thatoo** [comment]
et sous forme de module, ça donne ce qui suit mais le problème est le même, les vidéos doivent être ajoutées en dernier : 

```
<section class="mw1140p mod center">
	<ul id="page-video" class="module unstyled pan">
		<?php
		$module = module("page-video");
		foreach($module as $key => $val){
	 	?>
			 <li>
			 <article class="tj pll prl ptm">
				 <?php txt('page-video-texte-alpha'.$key)?>
			 </article>
			 <div class="tc pll prl">
					 <?php media("page-video-item-video-".$key, '480');?>
			 </div>
			 <article class="tj pll prl pbl">
					 <?php txt('page-video-texte-beta-'.$key)?>
			 </article>
			 </li>
		<?php
		}
		?>
	</ul>
</section>
```
