### ISSUE TITLE
Administration bloquée

### ISSUE THREAD

**Issue by Bekik** [simonvdfr/Translucide#35]
Bonjour,
J'ai fait une mauvaise manipulation et je me suis restreint l'administration de mon site. Je peux juste rajouter des pages et je n'ai donc plus accès à la totalité de l'administration.
Comment puis-je débloquer cette situation ?
Merci.

Problème résolu ! Je suis allée dans ma base de données.

**Comment by Thatoo** [comment]
Bonjour @Bekik
Pourrais-tu détailler comment tu t'es débloqué en allant dans la base de données?

**Comment by Bekik** [comment]
Bonjour @Thatoo,

J'avais une sauvegarde de ma base de données. Je l'ai donc importée sur mon serveur et j'ai exporté la table "user". Cette table je l'ai supprimée sur la base de mon site et j'ai importé la nouvelle sauvegardée.

J'ai pu voir du coup que dans le champ "auth", il doit y avoir :
edit-admin,edit-user,edit-nav,add-media,add-article,edit-article,add-page,edit-page

Lorsque j'étais bloquée je n'avais que "edit-admin".

**Comment by simonvdfr** [comment]
une alternative existe. si vous supprimez votre fichier config.php et que vous relancez l'installation (simplement en allant sur le site), une fois la procédure d'installation finie ça n'écrase pas les données (si la base existe-t-il ne la recréé pas) mais met à jour le mot de passe de l'utilisateur admin si vous rentrez le même mail et ça régénère le fichier config.php
