### ISSUE TITLE
$GLOBALS['toolbox'] color fait tout planter

### ISSUE THREAD

**Issue by Thatoo** [simonvdfr/Translucide#38]
L'outil "color" de $GLOBALS['toolbox'] dans config.php doit absolument être commenté dans la version master du 17/03/2022 sinon, Translucide reste bloqué dans l’administration, on ne peut plus ni sortir ni enregistrer.

**Comment by simonvdfr** [comment]
merci de ta vigilance, j'ai fait une correction et ajouté une note dans le fichier readme, pour bien configurer cette fonctionnalité.
