### ISSUE TITLE
Matomo integration

### ISSUE THREAD

**Issue by Thatoo** [simonvdfr/Translucide#39]
Je vois que plausible.io est intégré ce qui est cool. Serait-il possible d'intégrer Matomo aussi?

**Comment by simonvdfr** [comment]
il y a aussi google analytics.

ça serrait quoi le code a mettre dans le head ? il n'est pas possible de le mettre ailleurs dans le code ?

**Comment by Thatoo** [comment]
en effet, il y a google analytics aussi mais lui, il n'est pas "Simple and privacy-friendly"... Il est même dans le collimateur de l'UE qui le trouve quelque peu [ ] invasif / [ ] intrusif (au choix).

**Comment by Thatoo** [comment]
```
<!-- Matomo -->
<script type="text/javascript">
  var _paq = window._paq = window._paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//{$MATOMO_URL}/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', {$IDSITE}]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->
```

avec $MATOMO_URL et $IDSITE (un nombre) qui seraient à remplir dans config.php

Tout est expliqué là : https://developer.matomo.org/guides/tracking-javascript-guide
et au sujet de la gestion de cookies et du consentement d'être suivi : https://developer.matomo.org/guides/tracking-consent

D'ailleurs, je n'ai pas remarqué de bandeau demandant le consentement dans Translucide. C'est normal? Je maîtrise mal la question de ce bandeau (quand le mettre ou pas).

**Comment by simonvdfr** [comment]
je viens d'ajouter Matomo, avec 2 nouvelles variables à mettre dans la config pour que ça marche : 
`$GLOBALS['matomo_url'] = '';
$GLOBALS['matomo_id'] = '1';`
et il faut aussi mettre la variable `$_COOKIE['analytics'] = "activer";` pour que ça fonctionne (créer ce cookie après le consentement de l'utilisateur pour qu'il puisse ou non approuver l'utilisation de cookie).

Pour faire une popin de consentement je t'invite à t'inspirer du footer suivant, en le modifiant pour déposer le bon cookie : 
https://github.com/simonvdfr/Translucide-Plugin/blob/master/analytics/footer.php
