### ISSUE TITLE
Impossible d'ajouter un content autre que page d'accueil

### ISSUE THREAD

**Issue by Psychlem** [simonvdfr/Translucide#4]
Lorsque je souhaite ajouter des pages et des articles, le content est bien créé mais je ne peux pas y accèder. Je tombe sur erreur 404.

**Comment by simonvdfr** [comment]
Difficile d'évaluer le bug.
Quand vous créez une page avec le bouton "+" en bas à gauche vous mettez bien un titre (un permalien se crée automatiquement en dessous) et après vous êtes rediriger vers l'URL (du permalien en question) ?

Avez-vous un screenshot du navigateur que je voie l'URL...

Sinon on peut faire un teamviewer pour voir en live le problème, où vous passez à mon bureau si vous êtes sur Nantes :)
