### ISSUE TITLE
Problème d'affichage menu burger 480<screen<850

### ISSUE THREAD

**Issue by Thatoo** [simonvdfr/Translucide#40]
Bonsoir,

Avec la version master du moment, il y a un problème d'affichage avec le menu burger pour les résolution entre 480 et 850.
![image](https://user-images.githubusercontent.com/464782/159177614-2a1e6cad-b9d8-4d21-bfd9-79a38c0cd43b.png)

alors que inférieur à 480, ça s'affiche bien
![image](https://user-images.githubusercontent.com/464782/159177672-3e735451-63e5-43d9-b77e-c4e8de043917.png)

**Comment by Thatoo** [comment]
Ca semble lié à 		grid-auto-flow: column;

dans

```
/* GRIDS */
@media (min-width: 480px) {/* 544px */

	.medium-hidden { display: none !important; }

	.flex {
		display: flex;
		/* flex-wrap: wrap; Crée un bug */
	}

	/* INFO
	IE ne gère pas l'implicite du auto-flow. il est donc necessaire de spécifier le positionnement de chaque élément fils des grids en css avec :
		-ms-grid-column: x;
		-ms-grid-column: y;
	*/
	.grid {
		display: -ms-grid;
		display: grid;
		grid-auto-flow: column;
		grid-auto-columns: 1fr;
	}
```

**Comment by Thatoo** [comment]
J'ai changé
@media (min-width: 480px)
en
@media (min-width: 850px)

et c'est bon mais j'imagine que je vais faire face à d'autres problème plus tard du coup...

**Comment by simonvdfr** [comment]
merci pour l'alerte, c'est corrigé avec mon dernier commit
