### ISSUE TITLE
Erreur installation

### ISSUE THREAD

**Issue by loukasstoltz** [simonvdfr/Translucide#44]
Bonjour, 
Je suis entrain d'essayer le CMS avec un thème au hazard, l'installation a l'air de bien se dérouler, mais je rencontre une erreur :
**Warning: Trying to access array offset on value of type null in /Sites/backends/Translucide-cms/api/install.php on line 659**

Merci par avance ! Et good job! :-)

**Comment by simonvdfr** [comment]
Bonjour,

Je n'arrive pas à reproduire votre bug. j'ai faits quelque correction au niveau de l'installation, mais je n'ai pas cette erreur.
Pouvez-vous me coller ici le code que vous avez à cette ligne ?

**Comment by loukasstoltz** [comment]
Bonjour Simon et merci pour votre réactivité ! 
Je n'ai rien dit!  (oups!) 

J'avais téléchargé le zip hier soir et ça fonctionnait plutôt mal... ! 
La dernière mise à jour fonctionne parfaitement:  
-> Installation sans erreur, 
-> Redirection automatique vers page d'accueil
-> Crayon en bas à gauche comme convenu
-> Barre d'outils réapparue
-> Création de nouvelle page / Article ... ! 
Tout semble bon pour le thème "défaut" ! :-) 


Par contre le thème bara semble corrompu, mais on m'a expliqué qu'il y avait beaucoup de mises à jour pour de beaux projets! :-)

**Comment by simonvdfr** [comment]
oui les thèmes supplémentaires à disposition son très vieux. C'est possible qu'ils ne marchent pas avec la dernière version du CMS. Pour le moment le seul thème maintenu est celui-ci inclue dans le CMS `default`.
