### ISSUE TITLE
jquery sans googleapis

### ISSUE THREAD

**Issue by Thatoo** [simonvdfr/Translucide#45]
Quel est l'intérêt de garder des librairies externes sur googleapis? Ne partage t-on pas l'info de la présence de chacun de nos visiteurs avec google en agissant ainsi?
Pourquoi ne pas les auto-héberger? Est-ce moins "écolo" à cause de cache etc?

**Comment by simonvdfr** [comment]
c'est à chacun de jauger le pour et contre.

Là le choix par défaut est d'allers chercher sur le CDN le plus répandu pour potentialiser le fait qu'il serra surement déjà en cache dans le navigateur et donc ne pas télécharger une nouvelle fois les fichiers.

Vous pouvez changer et allers chercher les fichiers localement sur votre hébergement.

L'idéal serrait un CDN très rependu, qui utilise des datacenters écoconçus, de l’énergie renouvelable et qui n'est pas accolé au GAFAM, mais on n'est pas là :)

**Comment by Thatoo** [comment]
Si je l'ai mets dans le dossier api/ à côté des fichiers de lucide, serait-il possible de le mettre en cache tout comme lucide?
