### ISSUE TITLE
scandir dans ajax.admin.php échoue si $GLOBALS['path']

### ISSUE THREAD

**Issue by Thatoo** [simonvdfr/Translucide#47]
Bonsoir,

Je travaille actuellement à faire fonctionner Translucide dans Yunohost. Pour cela, j'ai besoin que le site ne soit pas à la racine du nom de domaine : https://nomdedomaine.net/site/
Lorsque je passe en mode admin et que j'enregistre, je me suis rendu compte que le template de la page n'était pas sauvegardé. J'ai enquêté et j'ai trouvé que lucid.edit.js fournissait la valeur de tpl préalablement récupérée par ajax.admin.php à la ligne 99

https://github.com/simonvdfr/Translucide/blob/master/api/ajax.admin.php#L99

`$scandir = array_diff(scandir($_SERVER['DOCUMENT_ROOT'].$GLOBALS['path']."theme/".$GLOBALS['theme'].($GLOBALS['theme']?"/":"")."tpl/"), array('..', '.'));`

Le problème c'est que dans le code source de la page généré lorsqu'on ne travaille pas à la racine du domn de domaine, on trouve l'erreur suivante :

`Warning:  scandir(/var/www/my_webapp/www//site/theme/nomdutheme/tpl/): failed to open dir: No such file or directory in /var/www/my_webapp/www/api/ajax.admin.php on line 99`

or le /site/ n'a rien à faire là. En effet, il n'existe pas dans l’arborescence des dossiers. J'ai donc modifié la ligne 99 ainsi,

`$scandir = array_diff(scandir($_SERVER['DOCUMENT_ROOT']."theme/".$GLOBALS['theme'].($GLOBALS['theme']?"/":"")."tpl/"), array('..', '.'));`

et ça fonctionne.

Y-a-t'il une raison à ce `$GLOBALS['path'].` qui semble de trop dans mon cas (le cas de Yunohost)?

**Comment by simonvdfr** [comment]
normalement quand on installe le cms dans un sous-dossier comme dans votre cas on spécifie justement dans `$GLOBALS['path'] = "/site/";` pour que ça fonctionne bien.
Je n'ai pas installé le cms dans un sous-dossier depuis un moment, il y a peut-être certaines choses qui ont bougé.

**Comment by Thatoo** [comment]
Non, maintenant je me retrouve avec /site/site...
`Warning: scandir(/var/www/my_webapp/www/site/site/theme/nomdutheme/tpl/): failed to open dir: No such file or directory in /var/www/my_webapp/www/api/ajax.admin.php on line 99`
donc ce n'est pas ça la bonne façon de faire.

**Comment by Thatoo** [comment]
Le plus simple pour faire fonctionner Translucide dans Yunohost avec nginx, ce serait de diviser `$GLOBALS['path'] = "";` en deux.
Garder `$GLOBALS['path'] = ""; ` mais ajouter un `$GLOBALS['subfolder'] = "";` qui remplacerait `$GLOBALS['path'] = "/";` dans le code à chaque fois qu'il sert pour désigner un sous-dossier, à chaque fois qu'on utilise `$_SERVER['DOCUMENT_ROOT']` comme par exemple
`$scandir = array_diff(scandir($_SERVER['DOCUMENT_ROOT'].$GLOBALS['path']."theme/".$GLOBALS['theme'].($GLOBALS['theme']?"/":"")."tpl/"), array('..', '.'));`
deviendrait
`$scandir = array_diff(scandir($_SERVER['DOCUMENT_ROOT'].$GLOBALS['subfolder']."theme/".$GLOBALS['theme'].($GLOBALS['theme']?"/":"")."tpl/"), array('..', '.'));`

Ainsi, en ayant
`$GLOBALS['path'] = "/site"; ` et `$GLOBALS['subfolder'] = "/";` je pourrais facilement résoudre mon problème et Translucide deviendrait compatible avec nginx et Yunohost.
La modification n'est pas énorme, il n'y a que 16 occurence de `$_SERVER['DOCUMENT_ROOT'].$GLOBALS['path']` à changer en `$_SERVER['DOCUMENT_ROOT'].$GLOBALS['subfolder']` et rajouter un $GLOBALS['subfolder'] = ""; dans config.php .

Je vais tester si ma théorie fonctionne en pratique et si oui, je ferais une PR en ce sens.

**Comment by Thatoo** [comment]
Ca fonctionne mais attention $GLOBALS['subfolder'] est une mauvaise idée car dans ajax.admin.php, il y a une variable $subfolder et ça entre en conflit.
J'ai donc utilisé $GLOBALS['sous-dossier'] .

Translucide fonctionne donc maintenant sur mon Raspbery pi qui tourne sous yunohost (avec nginx) dans un sous-dossier nginx (un /site/ virtuel, il est dans /var/www/my_webapp/www/ et non dans /var/www/my_webapp/www/site/).

Il serait donc assez facile de rendre Translucide installable en un click dans Yunohost avec comme fichier de conf nginx :

```
location @handler {
  rewrite ^/(.*)$ /site/index.php?^$1 last;
}

location /site/ {

    # Path to source
    alias /var/www/my_webapp/www/;

    # Default indexes and catch-all
    index index.php;
    try_files $uri $uri/ @handler;

    # Execute and serve PHP files
    location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        fastcgi_pass unix:/var/run/php/php7.3-fpm-my_webapp.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param REMOTE_USER $remote_user;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param SCRIPT_FILENAME $request_filename;
    }
    include conf.d/yunohost_panel.conf.inc;
}
```

**Comment by Thatoo** [comment]
ah non, il me reste un soucis, lucide.edit.js ne se charge pas et je crois que ça vient de la ligne 180 dans ajax.admin.php 
`script.src = path+"api/lucide.edit.js?<?=$GLOBALS['cache']?>";`
et plus précisément de ce "path" dont je n'arrive pas à comprendre ce qu'il vaut, d'où il vient.
Pourquoi ce n'est pas `$_SERVER['DOCUMENT_ROOT'].$GLOBALS['path']` comme d'habitude?

Je vais creuser la question.

**Comment by Thatoo** [comment]
Ne pourrions nous pas plutôt écrire l'url dans son ensemble avec un $GLOBALS['scheme'].$GLOBALS['domain'].$GLOBALS['path'] ?

**Comment by Thatoo** [comment]
résolue par https://github.com/simonvdfr/Translucide/pull/50
