### ISSUE TITLE
lien sur image dans module

### ISSUE THREAD

**Issue by Thatoo** [simonvdfr/Translucide#48]
Bonjour,

J'aimerais pouvoir créer un module d'image étant chacune clickable vers un lien différent.
J'ai pensé à 
```
<?php
$module = module("rs");
foreach($module as $key => $val)
{
?>
<li class="fl pas mas">
<a href="<?php make_url("rs-url".$key)?>"><?php media("rs-img-".$key, array('size' => '32x32', 'lazy' => true));?></a>
</li>
<?php
}
?>
</ul> -->
```
mais ça ne fonctionne pas, ou du moins, je n'arrive pas à entrer d'url.
Merci par avance pour toute aide apporté.

**Comment by mvigou** [comment]
Bonjour,

S'il s'agit d'un lien devant être editable, il faut utiliser la fonction `href()`

```
<?
$module = module("rs");
foreach($module as $key => $val)
{
?>
<li class="fl pas mas">
<a <?href("rs-url-".$key)?>><?php media("rs-img-".$key, array('size' => '32x32', 'lazy' => true));?></a>
</li>
<?php
}
?>
</ul> 
```

**Comment by Thatoo** [comment]
Ca fonctionne parfaitement. Merci!
