### ISSUE TITLE
Gestion des icones

### ISSUE THREAD

**Issue by Thatoo** [simonvdfr/Translucide#51]
Je ne comprends pas très bien la gestion des icônes. La volonté est d'avoir un fichier de font le plus petit possible et cela est louable mais si un webdev veut rajouter un icône c'est la galère.
Il y en a dans global.css, dans global.min.css, dans style.css et modifier les fichiers de font, ce n'est pas pratique.
Je propose de passer tout ça à https://fontello.com/

Qu'en pensez-vous?

**Comment by Thatoo** [comment]
Voici le dossier zip fontello correspondant à ce qui existe dans Translucide pour une transition en douceur
[fontello-a1666b3a.zip](https://github.com/simonvdfr/Translucide/files/8671588/fontello-a1666b3a.zip)

**Comment by simonvdfr** [comment]
désormais il n'y a plus de global.css. les fonts son listé dans ton style.css de ton thème.
si tu veux tu peux toujours forcer l'appel d'un fichier font spécifique dans config, c'est la variable `icons`
