### ISSUE TITLE
fire?

### ISSUE THREAD

**Issue by Thatoo** [simonvdfr/Translucide#52]
Bonjour, 
à quoi sert la classe
```
	.fire {
		opacity: 1 !important;
		transform: translate3d(0, 0, 0) !important;
	}
```
qui semble être utilde pour les animations (cf ligne 517-519 de lucide.init.js) mais je ne vois pas ce que ça apporte.
Pourrais-tu m'expliquer?

**Comment by simonvdfr** [comment]
oui, quand tu ajoutes la class `animation` à un élément, et l'animation que tu veux, `fade-in` par exemple, quand on scroll le js détecte que dans l'écran l’élément est présent et ajoute la class `fire` pour lancer l'animation.
