### ISSUE TITLE
Gestion des tags

### ISSUE THREAD

**Issue by Thatoo** [simonvdfr/Translucide#54]
Il semble que les tags ne fonctionnent que si le blog s'appelle Actualités ou du moins a pour url actualites à cause de la ligne 48 de article.php : 
`			<?php tag('actualites')?>`
Est-ce qu'on ne pourrait pas, juste avant cette ligne faire une requête pour savoir si il existe un blog, une query sql sur tpl=article-liste pour récupérer l'url et si elle existe, remplacer actualites par cette url?

**Comment by Thatoo** [comment]
@simonvdfr pourrais-tu m'expliquer comment se servir de

		// On rapatrie les infos du tag
		$sel_tag_info = $connect->query("SELECT * FROM ".$table_meta." WHERE type='tag-info' AND cle='".$tag."' LIMIT 1");
		$res_tag_info = $sel_tag_info->fetch_assoc();

dans index.php et 

	// Si sur page tag
	if(tag) 
	{
		// Ajoute les données prise dans le contenu
		data["tag-info"] = {};
		data["tag-info"]["title"] = data["tag"] = data["content"]["title"];
		data["tag-info"]["description"] = data["content"]["description"];
		data["tag-info"]["img"] = data["content"]["img"];
	}

dans lucide.edit.js

**Comment by simonvdfr** [comment]
pour que les tags fonctionnent il faut bien mettre le bon nom de zone qui doit être identique au permalink de la page qui liste les articles du blog (article-liste.php).

tu peux créer une page qui s'appelle `/blog` par exemple (qui utilise le tpl `article-liste.php`), et ta zone tag dans ton tpl `article.php` doit s'appeler  `<?php tag('blog')?>`, pour que la construction d'url se passe bien.

pour ta 2ème question :
dans la page article-liste.php il y a 2 données éditable spécifiques qui s'enregistre dans la table meta, ce sont les `tag-info`. ça permet de créer des pages de listing d'article plus qualitatif avec un texte `description` et une image d'illustration `img` (un picot par exemple)
