### ISSUE TITLE
Table 'translucide.content' doesn't exist in 

### ISSUE THREAD

**Issue by fistal** [simonvdfr/Translucide#61]
Bonjour,

Je découvre ce CMS avec curiosité.

J'ai installé un XAMPP 8.2.0-0 
Je lance mon serveur web et BDD (je setup au passage les acces login:pwd)
Je dezip "Translucide-master" dans le dossier web "htdocs"
Je créer une BDD "Translucide"
Je commence l'installation du CMS : setup des informations BDD + thème 
Je clique sur instalation -> j'ai le message suivant qui s'affiche en bas de page : 

Fatal error: Uncaught mysqli_sql_exception: Table 'translucide.content' doesn't exist in /Applications/XAMPP/xamppfiles/htdocs/Translucide-master/api/install.php:369 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/Translucide-master/api/install.php(369): mysqli->query('SELECT id FROM ...') #1 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/Translucide-master/api/install.php on line 369

J'ai l'impression qu'il veut accéder à une table de la BDD mais elle est vide... Je ne sais pas trop quoi faire :/ 

Si quelqu'un passe dans le coin :D

Merci de votre aide,
Ju

**Comment by simonvdfr** [comment]
je viens de push une correction. C'est php 8.1 qui ne gère pas les erreurs de la même façon et qui est plus radical en cas d'erreur et coupe complètement le processus.

**Comment by arnokastell** [comment]
Merci Simon pour la modif, ça fonctionne l'installation se fait et on arrive sur la page d'accueil du site. 
Par contre là il refuse d'afficher le mode admin ou le picto qui permet de se connecter en tant qu'admin et on a la page de base affichée comme visiteur. 

De ce que j'ai compris il aime pas la ligne 415 d'index.php : 
	tag = "<?=encode(@$tag)?>";

Dans le débogueur de firefox il m'affiche ça : 

tag = "<br />
<b>Deprecated</b>:  utf8_decode(): Passing null to parameter #1 ($string) of type string is deprecated in <b>D:\Programmes\MAMP\htdocs\kasteldev\api\function.php</b> on line <b>38</b><br />
";

Du coup j'ai l'impression que c'est la fonction de suppression des caractères indésirables qu'il a du mal à interpréter, la ligne 38 de function.php : 

	$value = strtolower(strtr(utf8_decode($value), implode($from), implode($to)));// Supp les caractères indésirables

Merci de ta réactivité en tout cas et le code est super bien commenté, ce qui fait que même un gros newbie comme moi peut essayer de comprendre la logique de fonctionnement c'est agréable ^^

**Comment by fistal** [comment]
Ok super, c'est tout bon ici sur l'installation.
En effet il y un soucis sur le CTA pour edit ou create. Il ne se passe rien sur l'IHM en console j'ai des erreurs. Mais il faudrait créer un ticket spécifique pour ce problème.

**Comment by simonvdfr** [comment]
je n'ai pas encore trop travaillé sur les versions supérieures à php 8.0. 
Sur php 8.2 utf8_decode est déprécié :( et ne fonctionne donc plus.
J'utilise cette fonction à pas mal d'endroits, donc le travail est conséquent...
il vaut effectivement mieux ouvrir un autre ticket pour ça et si vous le pouvez passer sous php 8.0

**Comment by simonvdfr** [comment]
pour infos je viens de mettre en ligne une mise à jour avec des corrections liées à php 8.2
