### ISSUE TITLE
Call to undefined function finfo_open()

### ISSUE THREAD

**Issue by arnokastell** [simonvdfr/Translucide#62]
Je suis passé en php 8.0.1, j'ai accès à la modification et validation des contenus nickel et j'ai essayé d'ajouter une image. 
bouton télécharger un fichier : ok
sélection de l'image : ok
bouton valider l'image : ok 
l'animation d'ajout se fait mais l'image ne charge pas sur le serveur et ne s'affiche pas et j'ai le message d'erreur suivant : 

Fatal error: Uncaught Error: Call to undefined function finfo_open() in D:\Programmes\MAMP\htdocs\kasteldev\api\ajax.admin.php:1782 Stack trace: #0 {main} thrown in D:\Programmes\MAMP\htdocs\kasteldev\api\ajax.admin.php on line 1782

Une idée :) ?

**Comment by simonvdfr** [comment]
Bonjour,

À tu vérifier que tu avais l'extension fileinfo d'activé dans php ? regarde avec un phpinfo(); ou/et aussi dans ton php.ini

**Comment by arnokastell** [comment]
Salut :), 

Effectivement je pensais que l'extension était activée mais en fait pas du tout. Du coup une fois activée ça fonctionne nickel, merci ! 
Je ferme le ticket, bonne journée à toi
