### ISSUE TITLE
Erreur php

### ISSUE THREAD

**Issue by IamHenri** [simonvdfr/Translucide#73]
Bonjour, 
j'a cet erreur en bas de page 
mode édition de la première news de mon site
Chrome / Ubuntu
ici : https://www.designerfonctionnel.com/integration/news-0 

Erreur uniquement en mode edition
Warning: main(): Couldn't fetch mysqli in /flex/storage/designerfonctionnel.com/site/www/integration/api/ajax.admin.php on line 2029

Dispo pour plus de précisions si besoin

**Comment by simonvdfr** [comment]
L'erreur est mineure, il semble ne pas arriver à fermer la connexion MySQL. Peut-être une configuration spécifique de MySQL. Chez quel hébergeur êtes-vous ?

Difficile de tester sans accès admin et au code.

**Comment by IamHenri** [comment]
C'était juste pour vous informer
Je suis chez scaleway.com anciennement online.net en mutualisé basique
Je vais tester à nouveau et voir si je peux trouver un moyen de reproduire le problème

**Comment by simonvdfr** [comment]
Peut-être qu'il n'arrive pas à fermer la connexion car il n'y en a pas eu. Il faudrait regarder dans quelle boucle il rentre pour arriver à cette erreur. Quelle est l'URL qui renvoie cette erreur dans vos networks ?
